---
- name: Update repositories cache and install
  hosts: all
  become: yes
  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Update all packages to the latest version
      apt:
        upgrade: dist