---
- name: Install Docker and Portainer
  hosts: all
  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Docker
      apt:
        name: docker
         